#include "stm32l476xx.h"

#include "timer.h"

#define SMCR_EXT_TRIG (0x7 << TIM_SMCR_TS_Pos)
#define CCMR_PWM 6

void timer_init() {
	RCC->APB2ENR |= RCC_APB2ENR_TIM8EN;
	
	TIM8->SMCR |= TIM_SMCR_SMS_3 | SMCR_EXT_TRIG;

	TIM8->CCMR1 |= CCMR_PWM << TIM_CCMR1_OC1M_Pos;
	TIM8->CCER |= TIM_CCER_CC1NE | TIM_CCER_CC1E;
	TIM8->ARR = 15;
	TIM8->CCR1 = 1;
	TIM8->BDTR |= TIM_BDTR_MOE;
	TIM8->CR1 |= TIM_CR1_OPM;
}
